/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author 01
 */
public class AddSubject extends javax.swing.JFrame {

    /**
     * Creates new form AddSubject
     */
    public AddSubject() {
        initComponents();
    }
    private ArrayList<Teacher>AllTeacher =new ArrayList<Teacher>();
    private ArrayList<Student>AllStudents =new ArrayList<Student>();
    private ArrayList<Teacher>SelectedTeacher =new ArrayList<Teacher>();
    private ArrayList<Student>SelectedStudents =new ArrayList<Student>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        System.out.println();
        AllTeacher=new ArrayList<>(School.mSchool.teachers);
        AllStudents=new ArrayList<>(School.mSchool.students);
        txtSubName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        btAddallStudents = new javax.swing.JButton();
        btAddSelectedStudent = new javax.swing.JButton();
        btRemoveAllStudents = new javax.swing.JButton();
        btRemoveSelectedStudents = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        DefaultListModel<Student> listModel = new DefaultListModel<>();
//        jList4 = new javax.swing.JList<>(new Vector<Student>(AllStudents));
        jList4 = new javax.swing.JList<>();
        btAddAllTeacher = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        btAddSelectedTeacher = new javax.swing.JButton();
        btRemoveAllTeacher = new javax.swing.JButton();
        btRemoveSelectedTeacher = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);

        txtSubName.setBackground(new java.awt.Color(242, 242, 242));
        txtSubName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Subject Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 0, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Sukar", 1, 16)); // NOI18N
        jLabel1.setText("selected Students");
        jLabel2.setFont(new java.awt.Font("Sukar", 1, 16)); // NOI18N
        jLabel2.setText("select Students");
        jList1.setModel(new AbstractListModel<String>() {
            final ArrayList<Student> strings = AllStudents;
            public int getSize() { return strings.size(); }
            public String getElementAt(int i) { return "id :"+ strings.get(i).getId() +" name:"+ strings.get(i).getName(); }
        });

        jScrollPane1.setViewportView(jList1);




        jScrollPane2.setViewportView(jList2);

        btAddallStudents.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btAddallStudents.setText(">>");
        btAddallStudents.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btAddallStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btAddallStudentsActionPerformed(evt);
            }
        });

        btAddSelectedStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btAddSelectedStudent.setText(">");
        btAddSelectedStudent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btAddSelectedStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btAddSelectedStudentActionPerformed(evt);
            }
        });

        btRemoveAllStudents.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btRemoveAllStudents.setText("<<");
        btRemoveAllStudents.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btRemoveAllStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btRemoveAllStudentsActionPerformed(evt);
            }
        });

        btRemoveSelectedStudents.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btRemoveSelectedStudents.setText("<");
        btRemoveSelectedStudents.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btRemoveSelectedStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btRemoveSelectedStudentsActionPerformed(evt);
            }
        });


        jList3.setModel(new AbstractListModel<String>() {
            final String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        btAddAllTeacher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btAddAllTeacher.setText(">>");
        btAddAllTeacher.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btAddAllTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btAddAllTeacherActionPerformed(evt);
            }
        });

        jList4.setModel(new AbstractListModel<String>() {
            final ArrayList<Teacher> strings = AllTeacher;
            public int getSize() { return strings.size(); }
            public String getElementAt(int i) { return "id :"+ strings.get(i).getId() +" name:"+ strings.get(i).getName(); }

        });
        jScrollPane4.setViewportView(jList4);

        btAddSelectedTeacher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btAddSelectedTeacher.setText(">");
        btAddSelectedTeacher.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btAddSelectedTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btAddSelectedTeacherActionPerformed(evt);
            }
        });

        btRemoveAllTeacher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btRemoveAllTeacher.setText("<<");
        btRemoveAllTeacher.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btRemoveAllTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btRemoveAllTeacherActionPerformed(evt);
            }
        });

        btRemoveSelectedTeacher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btRemoveSelectedTeacher.setText("<");
        btRemoveSelectedTeacher.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btRemoveSelectedTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btRemoveSelectedTeacherActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Sukar", 1, 16)); // NOI18N
        jLabel3.setText("selected Teachers");

        jLabel4.setFont(new java.awt.Font("Sukar", 1, 16)); // NOI18N
        jLabel4.setText("select Teachers");

        jLabel5.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        jLabel5.setText("Add new Subject");

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton9.setText("Add Subject");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btAdd(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btAddallStudents, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btAddSelectedStudent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btRemoveAllStudents, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btRemoveSelectedStudents, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(86, 86, 86)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(69, 69, 69)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btAddAllTeacher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAddSelectedTeacher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btRemoveAllTeacher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btRemoveSelectedTeacher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(txtSubName, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtSubName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAddallStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAddSelectedStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRemoveAllStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRemoveSelectedStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btAddAllTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAddSelectedTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRemoveAllTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRemoveSelectedTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        public  <E> boolean checkIfSelected(ArrayList<E> list ,E object ){
        if (list.contains(object)){
            System.out.println(object.getClass().getName()+ " this is in list");
            return true;
        }
        System.out.println("not in list");
        return false;
    }
    private void btAddSelectedStudentActionPerformed(ActionEvent evt) { // add selected
        int [] selectedIndices = jList1.getSelectedIndices();
        for (int i : selectedIndices) { // add the selected items to selectd box(array)
            if(!checkIfSelected(SelectedStudents,AllStudents.get(i))){
                SelectedStudents.add(AllStudents.get(i));
            }

        }
        jList2.setModel(new AbstractListModel<String>() { // set selected box with selected array
            public int getSize() { return SelectedStudents.size(); }
            public String getElementAt(int i) { return "id :"+ SelectedStudents.get(i).getId() +" name:"+ SelectedStudents.get(i).getName(); }
        });
    }

    private void btAddallStudentsActionPerformed(ActionEvent evt) { //add all selected

        if(AllStudents.size()!=0){ // add all to Student box
            SelectedStudents=new ArrayList<>(AllStudents);
        }
        jList2.setModel(new AbstractListModel<String>() { // set selected box with selected array
            public int getSize() { return SelectedStudents.size(); }
            public String getElementAt(int i) { return "id :"+ SelectedStudents.get(i).getId() +" name:"+ SelectedStudents.get(i).getName(); }
        });
    }

    private void btRemoveAllStudentsActionPerformed(ActionEvent evt) { // remove all
        SelectedStudents.clear();//rm all from main box

        jList2.setModel(new AbstractListModel<String>() { // set selected box with selected array
            public int getSize() { return SelectedStudents.size(); }
            public String getElementAt(int i) { return "id :"+ SelectedStudents.get(i).getId() +" name:"+ SelectedStudents.get(i).getName(); }
        });

    }
    private void btRemoveSelectedStudentsActionPerformed(ActionEvent evt) { // remove selected
        int [] selectedIndices = jList2.getSelectedIndices();
        for (int i= selectedIndices.length-1 ; i>=0;i--) { // add the selected items to selectd box(array)
            try {
                SelectedStudents.remove(selectedIndices[i]);
            }catch (Exception e) {
                System.out.println(e);
            }
        }
        jList2.setModel(new AbstractListModel<String>() { // set selected box with selected array
            public int getSize() { return SelectedStudents.size(); }
            public String getElementAt(int i) { return "id :"+ SelectedStudents.get(i).getId() +" name:"+ SelectedStudents.get(i).getName(); }
        });
    }

    private void btAddAllTeacherActionPerformed(ActionEvent evt) {
        if(AllTeacher.size()!=0){ // add all to Student box
            SelectedTeacher=new ArrayList<>(AllTeacher);
        }
        jList3.setModel(new AbstractListModel<String>() {
            public int getSize() { return SelectedTeacher.size(); }
            public String getElementAt(int i) { return "id :"+ SelectedTeacher.get(i).getId() +" name:"+ SelectedTeacher.get(i).getName(); }
        });
    }

    private void btAddSelectedTeacherActionPerformed(ActionEvent evt) {
        int [] selectedIndices = jList4.getSelectedIndices();
        System.out.println(Arrays.toString(selectedIndices));
        for (int i : selectedIndices) { // add the selected items to selectd box(array)
            SelectedTeacher.add(AllTeacher.get(i));
        }
        jList3.setModel(new AbstractListModel<String>() { // set selected box with selected array
            public int getSize() { return SelectedTeacher.size(); }
            public String getElementAt(int i) { return "id :"+ SelectedTeacher.get(i).getId() +" name:"+ SelectedTeacher.get(i).getName(); }
        });
    }

    private void btRemoveAllTeacherActionPerformed(ActionEvent evt) {
        SelectedTeacher.clear();//rm all from main box

        jList3.setModel(new AbstractListModel<String>() { // set selected box with selected array
            public int getSize() { return SelectedTeacher.size(); }
            public String getElementAt(int i) { return "id :"+ SelectedTeacher.get(i).getId() +" name:"+ SelectedTeacher.get(i).getName(); }
        });
    }

    private void btRemoveSelectedTeacherActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btRemoveSelectedTeacherActionPerformed
        int [] selectedIndices = jList3.getSelectedIndices();

        for (int i= selectedIndices.length-1 ; i>=0;i--) { // add the selected items to selectd box(array)
            try {
                SelectedTeacher.remove(selectedIndices[i]);
            }catch (Exception e) {
                System.out.println(e);
            }
        }
        jList3.setModel(new AbstractListModel<String>() { // set selected box with selected array
            public int getSize() { return SelectedTeacher.size(); }
            public String getElementAt(int i) { return "id :"+ SelectedTeacher.get(i).getId() +" name:"+ SelectedTeacher.get(i).getName(); }
        });
    }//GEN-LAST:event_btRemoveSelectedTeacherActionPerformed

    private void btAdd(ActionEvent evt) {
        try {
            School.mSchool.addSubject(new Subject(txtSubName.getText().toString(),SelectedTeacher,SelectedStudents));
        } catch (Exception e) {
            e.printStackTrace();
        }
        System.out.println(txtSubName.getText());
        System.out.println(SelectedStudents);
        System.out.println(SelectedTeacher);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSubject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddallStudents;
    private javax.swing.JButton btAddSelectedStudent;
    private javax.swing.JButton btRemoveAllStudents;
    private javax.swing.JButton btRemoveSelectedStudents;
    private javax.swing.JButton btAddAllTeacher;
    private javax.swing.JButton btAddSelectedTeacher;
    private javax.swing.JButton btRemoveAllTeacher;
    private javax.swing.JButton btRemoveSelectedTeacher;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList<String> jList3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField txtSubName;
    // End of variables declaration//GEN-END:variables
}
